version: "3"
services:

  mongo:
    image: mongo:3.6.19-xenial
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - .mongo-data:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo-data:
    driver: local
